feat: change code auth algo

diff --git a/scripts/fsrz/fsrz b/scripts/fsrz/fsrz
--- a/scripts/fsrz/fsrz
+++ b/scripts/fsrz/fsrz
@@ -19,9 +19,21 @@ CONFIG=$CONFIG_DIR/config
 
 ## ======
 
+function checkbin() 
+{
+    for f in $(echo $@)
+    do 
+        if [ ! $(command -v $f) ]; then 
+            echo "command:$f not found"
+            exit 1 
+        fi 
+    done 
+}
+
 ## doUpload upload logic
 function doUpload()
 {
+    checkbin curl jq md5sum cut date
     if [ ! -f $CONFIG ]; then 
         echo "config:$CONFIG not found, skip"
         exit 1
@@ -48,8 +60,11 @@ function doUpload()
     echo "read upload domain:$UPLOAD_DOMAIN"
     echo "read download domain:$DOWNLOAD_DOMAIN"
 
+    ts=$(date "+%s")
+    skcode=$(echo -n $AK":"$SK":$ts"|md5sum|cut -d ' ' -f1)
     downkey=$(curl -s -L -X POST "${SCHEMA}://${UPLOAD_DOMAIN}/upload/file" \
-    -H "x-fs-code: ${SK}" \
+    -H "x-fs-code: ${skcode}" \
+    -H "x-fs-ts: ${ts}" \
     --form "file=@\"$file\"" | jq -r ".data.down_key")
 
     echo "read downkey from server:$downkey"
